
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: python ratelimit.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
